### ISSUE TITLE
What is a PRN number?

### ISSUE THREAD

**Issue by sagaramruth** [cognitive-ninja/Mini-Voting-System#4]
can you brief me on executing the code?

**Comment by cognitive-ninja** [comment]
PRN number is unique id assigned to each student in our college. You can think of it as roll number (just with extra fields).
PRN structure: Lets take example of "2018BTECS00064"
First 4 characters i.e. "2018" explains the year in which this student got admission in college
Next 3 characters i.e. "BTE" explains this student is doing BTECH ("MTE" for MTECH like that)
Next 2 characters i.e. "CS" explains this student is in Computer Science branch
And last 5 characters i.e. "00064" is actually roll no in his class.
So this helps to pinpoint that student and work as unique id.

The screenshot for execution of code is available in this issue : https://github.com/cognitive-ninja/Mini-Voting-System/issues/1
(Recommended compiler : TurboC++, though you can use any other)

I hope this will be helpful for you. Once you be able to run program successfully, please convey here so that I can close this issue. And if you still got any questions, you can ask in this thread.
